
name: Build
on: [push, workflow_dispatch]
jobs:
  flutter_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter build apk --release
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: App-Release
          path: build/app/outputs/flutter-apk/app-release.apk
          
